parameters:
    pando_base_bundle.factory.entity.class: BlackBoxCode\Pando\BaseBundle\Factory\EntityFactory

services:
    pando_base_bundle.entity_factory:
        class: "%pando_base_bundle.factory.entity.class%"
        arguments:
            - %pando.entity.namespace%
