parameters:
    pando_base_bundle.tool.entity_generator.class: BlackBoxCode\Pando\Bundle\BaseBundle\Tools\EntityGenerator

services:
    pando_base_bundle.entity_generator:
        class: "%pando_base_bundle.tool.entity_generator.class%"
        arguments:
            - %pando_entity.namespace%
